MaintenanceModeService:
    Db:
        LogsConnString:
            settings-key: MaintenanceModeService-LogsConnString
            types:
              - AzureTableStorage
        DataConnString:
            settings-key: MaintenanceModeService-DataConnString
SlackNotifications:
    AzureQueue:
        ConnectionString:
            settings-key: SlackNotificationsConnString
            types:
                - AzureTableStorage
        QueueName:
            settings-key: SlackQueueName
MonitoringServiceClient:
    MonitoringServiceUrl:
        settings-key: MonitoringServiceUrl

