apiVersion: v1
kind: Service
metadata:
  labels:
    app: maintenance-mode
    environment: Development
  name: maintenance-mode
  namespace: services
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: maintenance-mode
  sessionAffinity: None
  type: ClusterIP
